name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # --- Spring Boot ---
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make Maven Wrapper executable
        run: chmod +x ./mvnw
        working-directory: ./springboot-application  

      - name: Build Spring Boot JAR
        run: ./mvnw clean package -DskipTests
        working-directory: ./springboot-application

      # --- Docker ---
      - name: Build Spring Boot Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/springboot-application:latest ./springboot-application  

      - name: Build Flask Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/flask-application:latest ./flask-application

      - name: Log in to Docker Hub using token
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker images to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/springboot-application:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/flask-application:latest
